version: '3.7'

services:
  client:
    image: mern-client
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  server:
    image: mern-server
    environment: 
      DATABASE_HOST: 'mongo'
    ports:
      - "8080:8080"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local